# Generated by Django 4.2 on 2026-03-20 15:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('medecin', 'Médecin du centre'), ('infirmier', 'Infirmier'), ('technicien', 'Technicien de laboratoire'), ('gestionnaire', 'Gestionnaire de stock'), ('responsable', 'Responsable de délivrance'), ('prescripteur', 'Prescripteur hospitalier'), ('autorite', 'Autorité sanitaire')], default='infirmier', max_length=20)),
                ('centre_ref', models.CharField(blank=True, default='Centre National de Transfusion Sanguine', max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], max_length=10)),
                ('message', models.TextField()),
                ('stock_actuel', models.IntegerField()),
                ('seuil', models.IntegerField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('resolue', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-date_alerte'],
            },
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('poids', models.IntegerField(help_text='Poids en kg')),
                ('telephone', models.CharField(max_length=20)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('type_donneur', models.CharField(choices=[('benevole', 'Bénévole'), ('familial', 'Don familial'), ('remunere', 'Rémunéré')], default='benevole', max_length=20)),
                ('credit_solidaire', models.IntegerField(default=0)),
                ('adresse', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_dernier_don', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='PocheSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_prelevement', models.DateField()),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('collecte', 'Collectée'), ('en_analyse', 'En analyse'), ('validee', 'Validée'), ('disponible', 'Disponible'), ('attribuee', 'Attribuée'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée'), ('rejetee', 'Rejetée')], default='collecte', max_length=20)),
                ('test_vih', models.BooleanField(blank=True, null=True, verbose_name='Test VIH négatif')),
                ('test_hepatite', models.BooleanField(blank=True, null=True, verbose_name='Test Hépatite négatif')),
                ('test_syphilis', models.BooleanField(blank=True, null=True, verbose_name='Test Syphilis négatif')),
                ('volume_ml', models.IntegerField(default=450)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('date_analyse', models.DateTimeField(blank=True, null=True)),
                ('analysee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poches_analysees', to=settings.AUTH_USER_MODEL)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poches_creees', to=settings.AUTH_USER_MODEL)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blood_bank.donneur')),
            ],
            options={
                'verbose_name': 'Poche de sang',
                'verbose_name_plural': 'Poches de sang',
                'ordering': ['-date_prelevement'],
            },
        ),
        migrations.CreateModel(
            name='MessageIEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('cible', models.CharField(choices=[('tous', 'Tous les donneurs'), ('benevoles', 'Donneurs bénévoles'), ('familiaux', 'Donneurs familiaux'), ('inactifs', 'Donneurs inactifs'), ('groupe_a', 'Groupe A'), ('groupe_b', 'Groupe B'), ('groupe_o', 'Groupe O'), ('groupe_ab', 'Groupe AB')], default='tous', max_length=20)),
                ('type_message', models.CharField(choices=[('sms', 'SMS'), ('ussd', 'USSD'), ('notification', 'Notification')], default='sms', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('envoye', models.BooleanField(default=False)),
                ('nombre_destinataires', models.IntegerField(default=0)),
                ('statut_envoi', models.CharField(blank=True, max_length=200)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message IEC',
                'verbose_name_plural': 'Messages IEC',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LogSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('reference_at', models.CharField(blank=True, max_length=100)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('donneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_bank.donneur')),
                ('message_iec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_bank.messageiec')),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='DemandeTransfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopital', models.CharField(max_length=200)),
                ('medecin', models.CharField(max_length=200)),
                ('groupe_requis', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantite', models.IntegerField(default=1)),
                ('urgence', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critique', 'Critique')], default='normal', max_length=10)),
                ('prix_final', models.IntegerField(default=0)),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('validee', 'Validée'), ('preparee', 'Préparée'), ('livree', 'Livrée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient_nom', models.CharField(blank=True, max_length=200)),
                ('telephone_contact', models.CharField(blank=True, max_length=20)),
                ('compatibilite_verifiee', models.BooleanField(default=False)),
                ('disponibilite_verifiee', models.BooleanField(default=False)),
                ('tracabilite_verifiee', models.BooleanField(default=False)),
                ('donneur_parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_parrainées', to='blood_bank.donneur')),
                ('poches_attribuees', models.ManyToManyField(blank=True, related_name='demandes', to='blood_bank.pochesang')),
                ('prescripteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_prescrites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de transfusion',
                'verbose_name_plural': 'Demandes de transfusion',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_standard', models.IntegerField(default=25000, help_text='Prix en FCFA')),
                ('prix_reduit', models.IntegerField(default=0, help_text='Prix réduit pour donneurs en FCFA')),
                ('seuil_credits', models.IntegerField(default=3, help_text='Crédits pour bénéficier du prix réduit')),
                ('seuil_alerte_stock', models.IntegerField(default=10, help_text="Seuil d'alerte stock par groupe")),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
