# Generated by Django 5.2.4 on 2026-03-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetransfusion',
            name='groupe_patient_verifie',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Groupe confirmé par le labo avant délivrance', max_length=3, verbose_name='Groupe sanguin vérifié du patient'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='type_produit',
            field=models.CharField(choices=[('sang_total', 'Sang total'), ('culot_erythrocytaire', 'Culot érythrocytaire'), ('culot_plaquettaire', 'Culot plaquettaire'), ('cryoprecipite', 'Cryoprécipité')], default='sang_total', max_length=30, verbose_name='Type de produit requis'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='verification_groupe_ok',
            field=models.BooleanField(default=False, verbose_name='Groupe patient vérifié et concordant'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='type_produit',
            field=models.CharField(choices=[('sang_total', 'Sang total'), ('culot_erythrocytaire', 'Culot érythrocytaire'), ('culot_plaquettaire', 'Culot plaquettaire'), ('cryoprecipite', 'Cryoprécipité')], default='sang_total', max_length=30, verbose_name='Type de produit sanguin'),
        ),
    ]
