# Generated by Django 5.2.4 on 2026-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochesang',
            name='lieu_collecte',
            field=models.CharField(blank=True, default='CNTS Brazzaville', max_length=200, verbose_name='Lieu de prélèvement'),
        ),
    ]
