# Generated by Django 5.2.4 on 2026-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_demandetransfusion_groupe_patient_verifie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', help_text='Laissez vide si inconnu — sera déterminé après analyses labo', max_length=3, verbose_name='Groupe sanguin'),
        ),
    ]
