# Generated by Django 5.2.4 on 2026-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_pochesang_lieu_collecte'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatdon',
            name='date_examen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='examen_medical_valide',
            field=models.BooleanField(default=False, verbose_name='Examen médical validé'),
        ),
        migrations.AlterField(
            model_name='demandetransfusion',
            name='type_produit',
            field=models.CharField(choices=[('sang_total', 'Sang total'), ('culot_erythrocytaire', 'Culot érythrocytaire'), ('culot_plaquettaire', 'Culot plaquettaire'), ('cryoprecipite', 'Cryoprécipité'), ('plasma_frais_congele', 'Plasma frais congelé')], default='sang_total', max_length=30, verbose_name='Type de produit requis'),
        ),
        migrations.AlterField(
            model_name='pochesang',
            name='statut',
            field=models.CharField(choices=[('collectee', 'Collectée'), ('en_analyse', 'En analyse'), ('validee', 'Validée'), ('disponible', 'Disponible'), ('attribuee', 'Attribuée'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée'), ('rejetee', 'Rejetée')], default='collecte', max_length=20),
        ),
    ]
