# Generated by Django 5.2.4 on 2026-03-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_alter_donneur_groupe_sanguin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='message_prix_solidaire',
            field=models.TextField(blank=True, default='Le prix solidaire est accordé aux donneurs réguliers et à leur famille selon décision du Directeur du CNTS.', help_text='Message explicatif affiché pour le prix solidaire'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prix_reduit',
            field=models.IntegerField(default=3750, help_text='Prix solidaire en FCFA — appliqué par le directeur aux donneurs réguliers et leur famille'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prix_standard',
            field=models.IntegerField(default=7500, help_text='Prix standard en FCFA (défaut CNTS Brazzaville : 7500 FCFA)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='seuil_alerte_stock',
            field=models.IntegerField(default=10, help_text="Seuil d'alerte stock par groupe sanguin"),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='seuil_credits',
            field=models.IntegerField(default=3, help_text='Nombre minimum de dons pour bénéficier du prix solidaire'),
        ),
    ]
