# Generated by Django 5.2.4 on 2026-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_candidatdon_date_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatdon',
            name='hemoglobine_ok',
            field=models.BooleanField(default=False, verbose_name='Hémoglobine suffisante'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='motif_inaptitude',
            field=models.TextField(blank=True, verbose_name="Motif d'inaptitude"),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='pas_antecedents_risque',
            field=models.BooleanField(default=False, verbose_name='Pas de comportement à risque'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='pas_de_maladie',
            field=models.BooleanField(default=False, verbose_name='Pas de maladie chronique/IST'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='pas_de_medicament',
            field=models.BooleanField(default=False, verbose_name='Pas de traitement incompatible'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='pas_fievre',
            field=models.BooleanField(default=False, verbose_name='Apyrétique (pas de fièvre)'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='pas_tuberculose',
            field=models.BooleanField(default=False, verbose_name="Pas d'antécédent tuberculose"),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='poids_ok',
            field=models.BooleanField(default=False, verbose_name='Poids ≥ 50 kg'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='tension',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tension (ex: 12/8)'),
        ),
        migrations.AddField(
            model_name='candidatdon',
            name='tension_ok',
            field=models.BooleanField(default=False, verbose_name='Tension normale'),
        ),
    ]
