# Generated by Django 5.2.4 on 2026-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_candidatdon_hemoglobine_ok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnregistrementDonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Pré‑enregistrement donneur',
                'verbose_name_plural': 'Pré‑enregistrements donneurs',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='donneur',
            name='date_retour_autorise',
            field=models.DateField(blank=True, null=True, verbose_name='Date à partir de laquelle il peut redonner'),
        ),
        migrations.AddField(
            model_name='donneur',
            name='date_suspension_paludisme',
            field=models.DateField(blank=True, null=True, verbose_name='Date de suspension pour paludisme'),
        ),
    ]
