# Generated by Django 5.2.4 on 2026-03-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_configuration_message_prix_solidaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('directeur', 'Directeur CNTS'), ('medecin', 'Médecin du centre'), ('infirmier', 'Infirmier'), ('technicien', 'Technicien de laboratoire'), ('gestionnaire', 'Gestionnaire de stock'), ('responsable', 'Responsable de délivrance'), ('prescripteur', 'Prescripteur hospitalier'), ('autorite', 'Autorité sanitaire')], default='infirmier', max_length=20),
        ),
        migrations.CreateModel(
            name='CarteDonneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de carte')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='cartes/qr/', verbose_name='QR Code')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cartes/photos/', verbose_name='Photo du donneur')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_expiration_carte', models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la carte")),
                ('active', models.BooleanField(default=True)),
                ('donneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to='blood_bank.donneur')),
                ('emise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte donneur',
                'verbose_name_plural': 'Cartes donneurs',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='ExamenMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_ok', models.BooleanField(default=False, verbose_name='Poids ≥ 50 kg')),
                ('tension_ok', models.BooleanField(default=False, verbose_name='Tension artérielle normale')),
                ('hemoglobine_ok', models.BooleanField(default=False, verbose_name="Taux d'hémoglobine suffisant")),
                ('pas_de_maladie', models.BooleanField(default=False, verbose_name='Pas de maladie chronique')),
                ('pas_de_medicament', models.BooleanField(default=False, verbose_name='Pas sous médication incompatible')),
                ('resultat', models.CharField(choices=[('apte', 'Apte au don'), ('inapte_temporaire', 'Inapte temporaire'), ('inapte_definitif', 'Inapte définitif'), ('en_attente', 'En attente de résultats')], default='en_attente', max_length=30)),
                ('motif_inaptitude', models.TextField(blank=True, verbose_name="Motif d'inaptitude si applicable")),
                ('date_examen', models.DateTimeField(auto_now_add=True)),
                ('date_prochain_examen', models.DateField(blank=True, null=True, verbose_name='Date du prochain examen (si inapte temporaire)')),
                ('donneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_medical', to='blood_bank.donneur')),
                ('medecin_examinateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen médical',
                'verbose_name_plural': 'Examens médicaux',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='VisiteurCNTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('type_visite', models.CharField(choices=[('rendu_poche', 'Rendu de poche transfusée'), ('retrait_resultats', 'Retrait de résultats'), ('renseignement', 'Renseignement')], default='rendu_poche', max_length=30)),
                ('nom_patient', models.CharField(blank=True, max_length=200, verbose_name='Nom du patient concerné')),
                ('nombre_poches_rendues', models.IntegerField(default=0, verbose_name='Nombre de poches rendues')),
                ('notes', models.TextField(blank=True)),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('sms_resultats_envoye', models.BooleanField(default=False)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visiteur CNTS',
                'verbose_name_plural': 'Visiteurs CNTS',
                'ordering': ['-date_visite'],
            },
        ),
    ]
