# Generated by Django 5.2.4 on 2026-04-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_preenregistrementdonneur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurcnts',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poids (kg)'),
        ),
    ]
