# Generated by Django 6.0.2 on 2026-03-25 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_alter_utilisateur_role_cartedonneur_examenmedical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hôpital',
                'verbose_name_plural': 'Hôpitaux',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='pochesang',
            name='test_hepatite',
        ),
        migrations.AddField(
            model_name='alertestock',
            name='type_produit',
            field=models.CharField(choices=[('sang_total', 'Sang total'), ('culot_erythrocytaire', 'Culot érythrocytaire'), ('culot_plaquettaire', 'Culot plaquettaire'), ('cryoprecipite', 'Cryoprécipité')], default='sang_total', max_length=30, verbose_name='Type de produit'),
        ),
        migrations.AddField(
            model_name='cartedonneur',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='Stockage temporaire du QR code en base64', verbose_name='Données du QR code (base64)'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='motif_solidaire',
            field=models.TextField(blank=True, help_text="Justification de l'application du prix solidaire", verbose_name='Motif de la réduction'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='prix_personnalise',
            field=models.IntegerField(blank=True, help_text='Prix fixé directement par le directeur', null=True, verbose_name='Prix personnalisé'),
        ),
        migrations.AddField(
            model_name='demandetransfusion',
            name='prix_solidaire_approuve',
            field=models.BooleanField(default=False, verbose_name='Prix solidaire approuvé par le directeur'),
        ),
        migrations.AddField(
            model_name='donneur',
            name='classification',
            field=models.CharField(choices=[('candidat', 'Candidat au don'), ('donneur', 'Donneur actif'), ('non_donneur', 'Non-donneur'), ('suspendu', 'Suspendu temporairement')], default='candidat', max_length=20, verbose_name='Classification donneur'),
        ),
        migrations.AddField(
            model_name='donneur',
            name='date_dernier_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneur',
            name='est_donneur_risque',
            field=models.BooleanField(default=False, help_text='Identifié lors des examens médicaux ou tests positifs', verbose_name='Donneur à risque'),
        ),
        migrations.AddField(
            model_name='donneur',
            name='motif_risque',
            field=models.TextField(blank=True, help_text='Raison pour laquelle le donneur est identifié comme à risque', verbose_name='Motif de risque'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='notes_examen',
            field=models.TextField(blank=True, verbose_name='Notes complémentaires'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='pas_allaitement',
            field=models.BooleanField(default=False, verbose_name="Pas d'allaitement en cours"),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='pas_grossesse',
            field=models.BooleanField(default=False, verbose_name='Pas de grossesse en cours (pour femmes)'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='pas_operation_recente',
            field=models.BooleanField(default=False, verbose_name="Pas d'opération récente (6 derniers mois)"),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='pas_tatouage',
            field=models.BooleanField(default=False, verbose_name='Pas de tatouage/percing récent (12 mois)'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='pas_voyage_risque',
            field=models.BooleanField(default=False, verbose_name='Pas de voyage en zone endémique récent'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_chagas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Maladie de Chagas négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_cytomegalovirus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Cytomégalovirus négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_ebv',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Virus Epstein-Barr négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_hepatite_b',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Hépatite B négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_hepatite_c',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Hépatite C négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_htlv',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test HTLV négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_paludisme',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Paludisme négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='test_parvovirus',
            field=models.BooleanField(blank=True, null=True, verbose_name='Test Parvovirus B19 négatif'),
        ),
        migrations.AddField(
            model_name='pochesang',
            name='tests_ok',
            field=models.BooleanField(default=False, verbose_name='Tous les tests sont négatifs'),
        ),
        migrations.AlterField(
            model_name='cartedonneur',
            name='emise_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_emises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examenmedical',
            name='hemoglobine_ok',
            field=models.BooleanField(default=False, verbose_name="Taux d'hémoglobine suffisant (≥ 12.5 g/dL)"),
        ),
        migrations.AlterField(
            model_name='messageiec',
            name='cible',
            field=models.CharField(choices=[('tous', 'Tous les donneurs'), ('benevoles', 'Donneurs bénévoles'), ('familiaux', 'Donneurs familiaux'), ('inactifs', 'Donneurs inactifs'), ('groupe_a', 'Groupe A'), ('groupe_b', 'Groupe B'), ('groupe_o', 'Groupe O'), ('groupe_ab', 'Groupe AB'), ('risque', 'Donneurs à risque')], default='tous', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidatDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('type_visite', models.CharField(choices=[('nouveau_donneur', 'Nouveau donneur'), ('donneur_existant', 'Donneur existant'), ('rendre_poche', 'Rendre une poche'), ('famille_patient', 'Famille de patient'), ('information', "Demande d'information")], max_length=30)),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('age_ok', models.BooleanField(default=False, verbose_name='Âge entre 18 et 65 ans')),
                ('poids_ok', models.BooleanField(default=False, verbose_name='Poids ≥ 50 kg')),
                ('bonne_sante', models.BooleanField(default=False, verbose_name='Bonne santé générale')),
                ('pas_don_recent', models.BooleanField(default=False, verbose_name='Pas de don dans les 56 derniers jours')),
                ('eligible_don', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('accueilli_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donneur_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_bank.donneur')),
            ],
            options={
                'verbose_name': 'Candidat au don',
                'verbose_name_plural': 'Candidats au don',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='TracabiliteEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('prelevement', 'Prélèvement'), ('transport_labo', 'Transport vers laboratoire'), ('reception_labo', 'Réception laboratoire'), ('analyse', 'Analyse en laboratoire'), ('validation', 'Validation des tests'), ('stockage', 'Stockage'), ('attribution', 'Attribution à une demande'), ('preparation', 'Préparation à la livraison'), ('transport_hopital', 'Transport vers hôpital'), ('livraison', "Livraison à l'hôpital"), ('transfusion', 'Transfusion au patient'), ('rejet', 'Rejet/Destruction')], max_length=30)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('temperature', models.FloatField(blank=True, help_text='Température en °C', null=True)),
                ('position', models.CharField(blank=True, help_text='Position/GPS', max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood_bank.hopital')),
                ('poche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracabilite', to='blood_bank.pochesang')),
            ],
            options={
                'verbose_name': 'Événement de traçabilité',
                'verbose_name_plural': 'Événements de traçabilité',
                'ordering': ['date_heure'],
            },
        ),
    ]
