# Generated by Django 6.0.2 on 2026-04-01 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0006_hopital_remove_pochesang_test_hepatite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visiteurcnts',
            options={'ordering': ['-date_visite'], 'verbose_name': 'Donneur familial', 'verbose_name_plural': 'Donneurs familiaux'},
        ),
        migrations.RemoveField(
            model_name='visiteurcnts',
            name='nombre_poches_rendues',
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='date_prelevement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de prélèvement'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='demande_associee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiteurs_associes', to='blood_bank.demandetransfusion', verbose_name='Demande de transfusion associée'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='groupe_patient',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Groupe sanguin du patient'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='hopital_patient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hôpital du patient'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='poche_associee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiteur_donneur', to='blood_bank.pochesang', verbose_name='Poche de sang associée'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='preleve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelevements_visiteurs', to=settings.AUTH_USER_MODEL, verbose_name='Prélevé par'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='prenom_patient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prénom du patient'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='statut_don',
            field=models.CharField(choices=[('en_attente', 'En attente de prélèvement'), ('preleve', 'Prélèvement effectué'), ('en_analyse', 'En analyse'), ('disponible', 'Disponible pour patient'), ('utilisee', 'Utilisée pour patient'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut du don'),
        ),
        migrations.AddField(
            model_name='visiteurcnts',
            name='telephone_patient',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du patient'),
        ),
        migrations.AlterField(
            model_name='visiteurcnts',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiteurs_enregistres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visiteurcnts',
            name='nom_complet',
            field=models.CharField(max_length=200, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='visiteurcnts',
            name='nom_patient',
            field=models.CharField(max_length=200, verbose_name='Nom du patient concerné'),
        ),
        migrations.AlterField(
            model_name='visiteurcnts',
            name='type_visite',
            field=models.CharField(choices=[('don_familial', 'Don familial (pour un patient)'), ('retrait_resultats', 'Retrait de résultats'), ('renseignement', 'Renseignement')], default='don_familial', max_length=30),
        ),
    ]
